apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: km6gqk6ks-nodejs 
  janus-idp.io/tekton: km6gqk6ks-nodejs
  backstage.io/kubernetes-id: km6gqk6ks-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: km6gqk6ks-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml